from typing import List, Dict, Any

class ChatbotService:
    INTENTS = [
        {
            "id": "how_to_register",
            "keywords": ["register", "sign up", "create account", "new farmer", "registration"],
            "question": "How do I register as a farmer?",
            "answer": "To register, enter your 10-digit mobile number to receive an OTP. After verification, provide your full name, 12-digit Aadhaar number, state, district, and village. Then select the crops you grow. You will receive a unique Farmer ID (e.g. FA000101)."
        },
        {
            "id": "how_to_book",
            "keywords": ["book", "booking", "slot", "appointment", "reserve"],
            "question": "How do I book a procurement slot?",
            "answer": "Log in to your FASAL account, go to 'Book Slot', choose your in-season crop, and enter the exact quantity in quintals. The system automatically assigns the nearest active procurement center, date, and shift."
        },
        {
            "id": "how_to_cancel",
            "keywords": ["cancel", "cancellation", "drop booking", "delete booking"],
            "question": "How can I cancel my booking?",
            "answer": "Go to 'My Bookings' on your dashboard and click 'Cancel' on any scheduled booking. The reserved slot capacity is immediately released for other farmers, and you will receive an SMS confirmation."
        },
        {
            "id": "how_to_rebook",
            "keywords": ["rebook", "reschedule", "change slot", "change date"],
            "question": "How do I reschedule or rebook a slot?",
            "answer": "You can click 'Rebook' on an eligible booking in your dashboard. The old slot is released, and the allocation engine will find the next earliest available slot for you."
        },
        {
            "id": "what_is_token",
            "keywords": ["token", "token number", "pass", "ticket", "sl code"],
            "question": "What is a procurement token?",
            "answer": "A token is a unique code generated by the backend (e.g. TK-20260906-0001). You must show this token when you arrive at the procurement center for weighing and verification."
        },
        {
            "id": "how_allocation_works",
            "keywords": ["allocation", "algorithm", "center assigned", "fifo", "how date assigned"],
            "question": "How does automatic slot allocation work?",
            "answer": "The system uses First-Book-First-Served (FIFO) ordering. Centers operate under a 7-hour (420 min) daily planning capacity. When a day reaches capacity, new bookings automatically roll over to the next available operating date."
        },
        {
            "id": "how_procurement_works",
            "keywords": ["procurement", "weighing", "unload", "arrival", "mandi process"],
            "question": "What happens on procurement day?",
            "answer": "Arrive at your assigned center during your designated shift window. Center staff verifies your token, weighs your crop on electronic weighbridges, and records the exact weight in quintals."
        },
        {
            "id": "how_payment_calculated",
            "keywords": ["payment", "rate", "money", "dbt", "how much money", "price"],
            "question": "How is my payment calculated?",
            "answer": "Payment is calculated using the official MSP rate: Payment Amount = Actual Measured Weight (Quintals) × Rate per Quintal. Payment is processed directly to your bank account via Direct Benefit Transfer (DBT)."
        },
        {
            "id": "support_contact",
            "keywords": ["support", "help", "contact", "toll free", "call", "helpline"],
            "question": "How do I contact support or book via IVR?",
            "answer": "You can call our simulated toll-free IVR line at 1800-FASAL-2026 (or use the simulated IVR console in the portal) to book, check status, or reschedule without needing internet access."
        }
    ]

    @classmethod
    def get_intents(cls) -> List[Dict[str, str]]:
        return [{"id": item["id"], "question": item["question"]} for item in cls.INTENTS]

    @classmethod
    def answer_query(cls, query_text: str) -> Dict[str, Any]:
        text_lower = query_text.lower().strip()
        best_match = None
        highest_score = 0

        for item in cls.INTENTS:
            score = 0
            if item["id"] == text_lower:
                return item
            for kw in item["keywords"]:
                if kw in text_lower:
                    score += len(kw)
            if score > highest_score:
                highest_score = score
                best_match = item

        if best_match and highest_score > 0:
            return {
                "matched": True,
                "question": best_match["question"],
                "answer": best_match["answer"],
                "intent_id": best_match["id"]
            }

        return {
            "matched": False,
            "question": query_text,
            "answer": "I'm sorry, I could not understand your query. Please pick from the FAQ topics above or call our helpline at 1800-FASAL-2026.",
            "intent_id": None
        }
